inherit_from: .rubocop_prettier.yml

plugins:
  - rubocop-rake
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

Layout/LineLength:
  Max: 200
  Enabled: true

Metrics/MethodLength:
  Max: 20
  Enabled: true

Naming/VariableNumber:
  EnforcedStyle: snake_case

RSpec/BeNil:
  EnforcedStyle: be
RSpec/DescribeClass:
  Exclude:
    - spec/open_meteo/integration/**/*
RSpecRails/HaveHttpStatus:
  Enabled: false
RSpec/ExampleLength:
  Max: 20
  Enabled: true
RSpec/MultipleExpectations:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false

Style/SafeNavigationChainLength:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
