inherit_from: .rubocop_prettier.yml

require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

Layout/LineLength:
  Max: 200
  Enabled: true

RSpec/BeNil:
  EnforcedStyle: be
RSpec/Rails/HaveHttpStatus:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
